spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      # Allow the Vite dev server (5173) to call the gateway (8080)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: ["*"]
            allowCredentials: false
      routes:
        - id: backend-api
          uri: ${backend.url}
          predicates:
            - Path=/api/**, /auth/**
        - id: backend-swagger
          uri: ${backend.url}
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**
        - id: backend-root
          uri: ${backend.url}
          predicates:
            - Path=/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO

# Central place to point the gateway at the backend; can be overridden via BACKEND_URL env var
backend:
  url: ${BACKEND_URL:http://127.0.0.1:8081}
