spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info